special_foods = {"vegan": [
    "Creamy Broccoli Vegan Pasta",
    "Butternut Squash Stuffed Shells",
    "Spaghetti Bolognese (Vegan Version)",
    "Creamy Pasta Pomodoro",
    "Best Vegan Pizza",
    "Creamy Vegan Pasta Salad",
    "Broccoli Pasta Salad",
    "Creamy Shiitake & Kale Pasta"
], "vegetarian":  [
    "Extra Vegetable Fried Rice",
    "Best Lentil Soup",
    "Crispy Baked Falafel",
    "Epic Vegetarian Tacos",
    "Peanut Slaw with Soba Noodles",
    "Walnut-Lentil Bolognese",
    "Vegetable Soup",
    "Roasted Sweet Potato Salad",
    "Shaved Brussels Sprout Salad with Creamy Maple Dressing",
    "Vegetarian Burrito Bowl with Avocado Crema"
], "halal": [
    "Turmeric Chicken on Flatbread",
    "Stir-Fried Chicken and Vegetables",
    "Sweet and Sour Shrimp",
    "Salisbury Steak and Sauce",
    "Classic Butter Chicken",
    "Chicken Liver Adobo (Adobong Atay)",
    "Chicken Shawarma Rice",
    "Scrambled Eggs with Mushrooms",
    "Authentic Chicken Maqluba",
    "Saucy Halal Beef on Bread",
    "Halal Quinoa Kibbeh Labaniyeh"
], "kosher": [
    "Turmeric Chicken on Flatbread",
    "Stir-Fried Chicken and Vegetables",
    "Sweet and Sour Shrimp",
    "Salisbury Steak and Sauce",
    "Classic Butter Chicken",
    "Chicken Liver Adobo (Adobong Atay)",
    "Chicken Shawarma Rice",
    "Spaghetti Squash Sopa Seca (Paleo and Gluten-Free)",
    "Chili with Butternut Squash",
    "Chicken and Peppers",
    "Ramen Shakshuka",
    "Avocado Stuffed Salmon with Wild Rice",
    "Mushroom Souffle",
    "Roasted Fruit Salad",
    "Fruit Salad with Strawberry Sauce",
    "Squash and Pear Soup",
    "Roasted String Beans with Apricots and Dates"
], "allergies": [
    "Turmeric Chicken on Flatbread",
    "Stir-Fried Chicken and Vegetables",
    "Sweet and Sour Shrimp",
    "Salisbury Steak and Sauce",
    "Classic Butter Chicken",
    "Chicken Liver Adobo (Adobong Atay)",
    "Chicken Shawarma Rice",
    "Spaghetti Squash Sopa Seca (Paleo and Gluten-Free)",
    "Chili with Buttern"]
}
